const gameConfig = {
  keyLimit: 13,
  handlePrecisionRatio: 25,
  arenaMeshesCount: 4,
  arenaImportpath: '/arena.gltf',
  arenaMaterialName: 'arenaWireframe',
  areneId: 'arena',
  gameDead: 0,
  hitIndicatorFrontColor: { r: 1, g: 0, b: 0 },
  hitIndicatorBackColor: { r: 0, g: 1, b: 0 },
  hitIndicatorDebugMeshName: 'hitIndicatorDebugMesh',
  hitIndicatorDebugMaterialName: 'hitIndicatorDebugMaterial',
  hitDiskMaterialName: 'hitDiskMaterial',
  hitDiskAlpha: 1,
  hitDiskStartColor: { r: 0, g: 1, b: 0 },
  hitDiskEndColor: { r: 1, g: 0, b: 0 },
  hitDiskMeshName: 'diskMesh',
  hitLinesMeshName: 'linesMesh',
  guiTextureName: 'GUI',
  guiTextureWidth: 600,
  guiTextureHeight: 400,
  guiHealtControlName: 'healthMeter',
  guiManaControlName: 'manaMeter',
  goalId1: 'goal_1',
  goalId2: 'goal_2',
  rootMesh: '__root__',
  hintFontPath: '/Orbitron_Regular.json'
};

export default gameConfig;
